# config/packages/doctrine_migrations.yaml
doctrine_migrations:
    migrations_paths:
        # ONLY include Landlord here for the default config
        'App\Migrations\Landlord': '%kernel.project_dir%/migrations/Landlord'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'